Desktop version
nedjwab/MyPortfolio pull request #11
Opened 2022-03-24 20:45 UTC by nedjwab

- Add HTML to the desktop version.
- Add CSS to the desktop version.
- Update README.ms file.
- Fix linter errors.

2022-03-24 22:01 UTC, moise10r requested changes
### Hi @nedjwab,

Great work on making the changes requested by a previous reviewer 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!


### To highlight 💪🏻

- No linter errors. ✔️ 
- Github flow was correctly used.  ✔️   
- Good commit messages ✔️ 
- Descriptive README file.  ✔️ 
 👍  Good job!

<img src="https://media4.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 22:01 UTC, moise10r commented on index.html
>                      <ul class="infolist">
- [ ] Great job so far :+1: but what do you think if you add an other media query for the desktop 

||`min-width: 1080px`|     flex-direction: column; ||
 |-|---------|----------|-|
|-|![012345](https://user-images.githubusercontent.com/57562869/160013329-2b05174f-5ceb-41c4-a94f-426ee3fe4f75.png) | ![56789](https://user-images.githubusercontent.com/57562869/160013370-ba6038d6-65ca-46ce-b272-04f2f3029667.png)|-|

2022-03-24 22:01 UTC, moise10r commented on style.css
>    }
- [ ] Great job so far :+1: but what do you think if you add another media query for the Desktop breakpoint in the CSS file. the value for `min-width: 992 px` (any value between 768 and 1440 is ok.) so that you can give to the card container a `flex-direction: column;` property

||`min-width: 1080px`|     flex-direction: column; ||
 |-|---------|----------|-|
|-|![012345](https://user-images.githubusercontent.com/57562869/160013329-2b05174f-5ceb-41c4-a94f-426ee3fe4f75.png) | ![56789](https://user-images.githubusercontent.com/57562869/160013370-ba6038d6-65ca-46ce-b272-04f2f3029667.png)|-|

2022-03-24 22:01 UTC, moise10r commented on style.css
> -    padding:0 400px;
- [ OPTIONAL] Please Always the best practice to use the classes attribute for your CSS instead of using ID selector. kindly avoid using the ID select use class selector instead

2022-03-24 22:01 UTC, moise10r commented on style.css
> +  }
- [ ] According to the requirement you must stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Kindly use the same color as on the original design `color: #344563;`

2022-03-25 08:16 UTC, nedjwab commented on style.css
>    }
@moise10r, thank you for your feedback. For this Section, I have just adjusted my media queries so the cards can be adjusted properly to any resolution between (768 and 1440).

2022-03-25 09:32 UTC, FrederickMih approved these changes
# Status : :tada: 
![Approved](https://user-images.githubusercontent.com/63087491/160094207-6e06b3a4-ee01-459c-8e21-c6a58d2edbfb.jpg)


Hi @nedjwab , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 09:41 UTC, merged